// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm4Gpk2elmVGm5CkFshLhq4mFnuh0tdN4',
    appId: '1:605648654273:web:b2388a289dcee0340ae940',
    messagingSenderId: '605648654273',
    projectId: 'stock-flutter-partiel',
    authDomain: 'stock-flutter-partiel.firebaseapp.com',
    storageBucket: 'stock-flutter-partiel.firebasestorage.app',
    measurementId: 'G-F6Z49R1TR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDATaNU-h9Szq3eyQKURwpTwfBqsh8GS2E',
    appId: '1:605648654273:android:a80347018cc452620ae940',
    messagingSenderId: '605648654273',
    projectId: 'stock-flutter-partiel',
    storageBucket: 'stock-flutter-partiel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx5ngbuWfh9zt_hbkx2I1Q3nnTQFuY9mA',
    appId: '1:605648654273:ios:b08b262ed6469a5b0ae940',
    messagingSenderId: '605648654273',
    projectId: 'stock-flutter-partiel',
    storageBucket: 'stock-flutter-partiel.firebasestorage.app',
    iosBundleId: 'com.example.stockFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx5ngbuWfh9zt_hbkx2I1Q3nnTQFuY9mA',
    appId: '1:605648654273:ios:b08b262ed6469a5b0ae940',
    messagingSenderId: '605648654273',
    projectId: 'stock-flutter-partiel',
    storageBucket: 'stock-flutter-partiel.firebasestorage.app',
    iosBundleId: 'com.example.stockFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAm4Gpk2elmVGm5CkFshLhq4mFnuh0tdN4',
    appId: '1:605648654273:web:1b35347d13eac1c30ae940',
    messagingSenderId: '605648654273',
    projectId: 'stock-flutter-partiel',
    authDomain: 'stock-flutter-partiel.firebaseapp.com',
    storageBucket: 'stock-flutter-partiel.firebasestorage.app',
    measurementId: 'G-RL09T95F85',
  );
}
